---
name: ((deployment_name))

# NOTE: this deployment requires the BOSH DNS add-on to be collocated by some
# runtime-config to be setup on the BOSH Director.
#
# See:
#   - https://bosh.io/docs/dns/#dns-release
#   - https://github.com/cloudfoundry/bosh-deployment/blob/master/runtime-configs/dns.yml
features:
  use_dns_addresses: true

instance_groups:
  - name: db
    instances: 1
    azs: [z1]
    jobs:
      - name: postgres
        release: postgres
        properties:
          databases: 
            databases:
              - name: kong
                citext: true
                tag: kong-db-tag
              - name: konga
                citext: true
                tag: konga-db-tag
            port: 5432
            roles:
              - name: kong
                password: ((kong_db_password))
                tag: kong-db-tag
              - name: konga
                password: ((konga_db_password))
                tag: konga-db-tag
    persistent_disk_type: default
    stemcell: default
    vm_type: default
    networks:
      - name: ((network_name))

  - name: kong
    instances: 1
    azs: [z1, z2, z3]
    jobs:
      - name: &kong_redirect_plugin_name kong-redirect-plugin
        release: gk-kong
      - name: kong
        release: gk-kong
        properties:
          extra_plugin_packages:
            - *kong_redirect_plugin_name
          extra_plugins:
            - redirect
          proxy:
            http_enabled: false
            tls:
              cert: ((kong_tls))
            injected_headers: []
          admin:
            http_enabled: false
            tls:
              cert: ((kong_tls))
            basic_auth:
              password: ((kong_admin_password))
      - name: bpm
        release: bpm
      - name: smoke-tests
        release: gk-kong
    stemcell: default
    vm_type: default
    networks:
      - name: ((network_name))

  - name: ui
    instances: 1
    azs: [z1, z2, z3]
    jobs:
      - name: konga
        release: gk-kong
        properties:
          log_level: debug
          token_secret: ((konga_token_secret))
          admin:
            password:  ((konga_admin_password))
          tls:
            cert: ((kong_tls))
          trusted_ca_certificates: |
            ((kong_tls.ca))
      - name: bpm
        release: bpm
      - name: ca_certs
        release: os-conf
        properties:
          certs: |
            ((kong_ca.certificate))
    stemcell: default
    vm_type: default
    networks:
      - name: ((network_name))

variables:
  - name: kong_db_password
    type: password
  - name: kong_admin_password
    type: password
  - name: kong_ca
    type: certificate
    options:
      is_ca: true
      common_name: kong-ca
    update_mode: converge
  - name: kong_tls
    type: certificate
    options:
      ca: kong_ca
      common_name: kong.((network_name)).((deployment_name)).bosh
      alternative_names:
        - "*.kong.((network_name)).((deployment_name)).bosh"
        - "127.0.0.1"
        - "*.ui.((network_name)).((deployment_name)).bosh"
    consumes:
      alternative_name: { from: kong }
    update_mode: converge
  - name: konga_db_password
    type: password
  - name: konga_token_secret
    type: password
  - name: konga_admin_password
    type: password

stemcells:
  - alias: default
    os: ubuntu-bionic
    version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: gk-kong
  sha1: 2f6c080c0f713e8a4bb82a589eb9d26b0a3137d9
  stemcell:
    os: ubuntu-bionic
    version: "0.28"
  url: https://s3.eu-west-3.amazonaws.com/gk-kong-boshrelease/compiled-releases/gk-kong/gk-kong-2.1.0-ubuntu-bionic-0.28-20210501-084609-019339587-20210501084612.tgz
  version: 2.1.0
- name: bpm
  sha1: de0d7d55cb88c24351a7a446f0c4647908a612e7
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.4.7
  version: 1.4.7
- name: postgres
  sha1: f130ebc9c4abf023e955e2fc7b7ea3bb6a64682a
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=53
  version: "53"
- name: os-conf
  sha1: 0f88a29315d8d9f900bb30a81c0eaf6d34a61639
  url: https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=22.3.0
  version: 22.3.0
