---
name: ((deployment_name))

instance_groups:
  - name: db
    instances: 1
    azs: [z1]
    jobs:
      - name: postgres
        release: postgres
        properties:
          databases: 
            databases:
              - name: kong
                citext: true
                tag: kong-db-tag
              - name: konga
                citext: true
                tag: konga-db-tag
            port: 5432
            roles:
              - name: kong
                password: ((kong_db_password))
                tag: kong-db-tag
              - name: konga
                password: ((konga_db_password))
                tag: konga-db-tag
    persistent_disk_type: default
    stemcell: default
    vm_type: default
    networks:
      - name: ((network_name))

  - name: kong
    instances: 1
    azs: [z1, z2, z3]
    jobs:
      - name: &kong_redirect_plugin_name kong-redirect-plugin
        release: gk-kong
      - name: kong
        release: gk-kong
        properties:
          extra_plugin_packages:
            - *kong_redirect_plugin_name
          extra_plugins:
            - redirect
          proxy:
            http_enabled: false
            tls:
              cert: ((kong_tls))
          admin:
            http_enabled: false
            tls:
              cert: ((kong_tls))
            basic_auth:
              password: ((kong_admin_password))
      - name: bpm
        release: bpm
      - name: smoke-tests
        release: gk-kong
    stemcell: default
    vm_type: default
    networks:
      - name: ((network_name))

  - name: ui
    instances: 1
    azs: [z1, z2, z3]
    jobs:
      - name: konga
        release: gk-kong
        properties:
          log_level: debug
          token_secret: ((konga_token_secret))
          admin:
            password:  ((konga_admin_password))
          tls:
            cert: ((kong_tls))
          trusted_ca_certificates: |
            ((kong_tls.ca))
      - name: bpm
        release: bpm
      - name: ca_certs
        release: os-conf
        properties:
          certs: |
            ((kong_ca.certificate))
    stemcell: default
    vm_type: default
    networks:
      - name: ((network_name))

variables:
  - name: kong_db_password
    type: password
  - name: kong_admin_password
    type: password
  - name: kong_ca
    type: certificate
    options:
      is_ca: true
      common_name: kong-ca
  - name: kong_tls
    type: certificate
    options:
      ca: kong_ca
      common_name: kong.((network_name)).((deployment_name)).bosh
      alternative_names:
        - "*.kong.((network_name)).((deployment_name)).bosh"
        - "127.0.0.1"
        - "*.ui.((network_name)).((deployment_name)).bosh"
  - name: konga_db_password
    type: password
  - name: konga_token_secret
    type: password
  - name: konga_admin_password
    type: password

features:
  use_dns_addresses: true

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: gk-kong
  sha1: 0634844831f5627f9168ef7648fe701548e34f95
  stemcell:
    os: ubuntu-xenial
    version: "315.13"
  url: https://s3.eu-west-3.amazonaws.com/gk-kong-boshrelease/compiled-releases/gk-kong/gk-kong-1.1.0-ubuntu-xenial-315.13-20190509-213511-820272019-20190509213512.tgz
  version: 1.1.0
- name: bpm
  sha1: 4b6ebfdaa467c04855528172b099e565d679e0f5
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.13.0
  version: 0.13.0
- name: postgres
  sha1: b9652c22cbc664d60af82b534624e3f63753feb5
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=32
  version: "32"
- name: os-conf
  sha1: a60187f038d45e2886db9df82b72a9ab5fdcc49d
  url: https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=20.0.0
  version: 20.0.0
