---
name: ((deployment_name))

instance_groups:
  - name: database
    instances: 1
    azs: [z1]
    jobs:
      - name: postgres
        release: postgres
        properties:
          databases: 
            databases:
              - name: kong
                citext: true
                tag: kong-db-tag
            port: 5432
            roles:
              - name: kong
                password: ((kong_db_password))
                tag: kong-db-tag
    persistent_disk_type: default
    stemcell: default
    vm_type: default
    networks:
      - name: ((network_name))

  - name: kong
    instances: 1
    azs: [z1, z2, z3]
    jobs:
      - name: &kong_redirect_plugin_name kong-redirect-plugin
        release: gk-kong
      - name: kong
        release: gk-kong
        properties:
          extra_plugin_packages:
            - *kong_redirect_plugin_name
          extra_plugins:
            - redirect
          proxy:
            tls:
              cert: ((kong_tls))
          admin:
            tls:
              cert: ((kong_tls))
            basic_auth:
              password: ((kong_admin_password))
      - name: bpm
        release: bpm
      - name: smoke-tests
        release: gk-kong
    stemcell: default
    vm_type: default
    networks:
      - name: ((network_name))

variables:
  - name: kong_db_password
    type: password
  - name: kong_admin_password
    type: password
  - name: kong_ca
    type: certificate
    options:
      is_ca: true
      common_name: kong-ca
  - name: kong_tls
    type: certificate
    options:
      ca: kong_ca
      common_name: kong.((network_name)).((deployment_name)).bosh
      alternative_names:
        - "*.kong.((network_name)).((deployment_name)).bosh"
        - "127.0.0.1"

features:
  use_dns_addresses: true

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
  - name: gk-kong
    version: "1.1.0"
    url: https://github.com/gstackio/gk-kong-boshrelease/releases/download/v1.1.0/gk-kong-1.1.0.tgz
    sha1: b2a1b7fd1af0cd64719c51c95f0bab67306ff5e6
  - name: bpm
    version: "0.13.0"
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.13.0
    sha1: 4b6ebfdaa467c04855528172b099e565d679e0f5
  - name: postgres
    version: "30"
    url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=30
    sha1: a798999d29b9f5aa12035cff907b26674b491200
