---

resources:
  - name: gk-ops-image
    type: docker-image
    icon: docker
    source:
      repository: harbor.ci.gstack.io/gstack/gk-ops
      username: ((docker_registry_username))
      password: ((docker-registry-password))

  - name: gk-automation
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/gk-automation.git
      branch: master
      private_key: ((github-private-key))

  - name: kong-gh-release
    type: github-release
    icon: github
    source:
      owner: kong
      repository: kong
      pre_release: false
      tag_filter: (1\.0\.\d+)
      access_token: ((github-access-token))

  - name: bpm-bosh-io-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bpm-release

  - name: postgres-bosh-io-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/postgres-release

  - name: os-conf-bosh-io-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/os-conf-release

  - name: kong-boshrelease-master
    type: git
    icon: github
    source:
      uri: ((kong_release_git_uri))
      branch: master
      private_key: ((github-private-key))

jobs:
  - name: detect-kong
    plan:
      - in_parallel:
          - get: kong-gh-release
            trigger: true
            params:
              globs: []
              include_source_tarball: true
          - get: kong-boshrelease-master
          - get: gk-automation
          - get: gk-ops-image

      - task: checkout-branch
        image: gk-ops-image
        file: gk-automation/tasks/git/checkout-branch.yml
        input_mapping:
          artifact-version: kong-gh-release
          repo:             kong-boshrelease-master
        params:
          BRANCH_NAME_TEMPLATE: bump-kong-${artifact_version}
          GITHUB_PRIVATE_KEY:   ((github-private-key))

      - task: bump-blob
        image: gk-ops-image
        file: gk-automation/tasks/boshrelease/bump-blob.yml
        input_mapping:
          artifact-release: kong-gh-release
          boshrelease-repo: repo-branched
        params:
          ARTIFACT_HUMAN_NAME:      Kong source code
          ARTIFACT_FILE_TEMPLATE:   source.tar.gz
          BLOB_PATH_AWK_PATTERN:    kong\/kong-[0-9.]+\.tar\.gz
          BLOB_PATH_TEMPLATE:       kong/kong-${artifact_version}.tar.gz
          PACKAGE_NAME:             kong
          ARTIFACT_REF_VARS_PREFIX: KONG

      - task: git-commit
        image: gk-ops-image
        file: gk-automation/tasks/git/commit.yml
        input_mapping:
          repo: boshrelease-repo-bumped
        params:
          GIT_COMMIT_NAME:  ((git-commit-name))
          GIT_COMMIT_EMAIL: ((git-commit-email))

      - task: upload-blobs
        image: gk-ops-image
        file: gk-automation/tasks/boshrelease/upload-blobs.yml
        input_mapping:
          boshrelease-repo: repo-committed
        params:
          S3_ACCESS_KEY_ID: ((aws-access-key))
          S3_SECRET_ACCESS_KEY: ((aws-secret-key))

      - task: git-commit
        image: gk-ops-image
        file: gk-automation/tasks/git/commit.yml
        input_mapping:
          repo: boshrelease-repo-blobs-uploaded
        params:
          GIT_COMMIT_MESSAGE: "Uploaded blob for new Kong source code"
          GIT_COMMIT_NAME:    ((git-commit-name))
          GIT_COMMIT_EMAIL:   ((git-commit-email))

      - task: git-push
        image: gk-ops-image
        file: gk-automation/tasks/git/push-to-branch.yml
        input_mapping:
          repo: repo-committed
        params:
          GIT_URI:            ((kong_release_git_uri))
          GITHUB_PRIVATE_KEY: ((github-private-key))

      - task: compose-pr
        image: gk-ops-image
        file: gk-automation/tasks/boshrelease/compose-pr.yml
        params:
          ARTIFACT_HUMAN_NAME: Kong
          RELEASE_NOTES_URL_TMPL: https://github.com/Kong/kong/blob/${artifact_version}/CHANGELOG.md

      - task: submit-pr
        image: gk-ops-image
        file: gk-automation/tasks/github/submit-pr.yml
        params:
          GH_ACCESS_TOKEN: ((github-access-token))
          GH_OWNER:        gstackio
          GH_REPO:         gk-kong-boshrelease

  - name: detect-bpm
    serial: true
    serial_groups: [ detect ]
    plan:
      - in_parallel:
          - get: bpm-bosh-io-release
            trigger: true
            params: { tarball: false }
          - get: kong-boshrelease-master
          - get: gk-automation
          - get: gk-ops-image

      - task: bump-bpm
        image: gk-ops-image
        file: gk-automation/tasks/boshrelease/depl-manifest-release-bump.yml
        input_mapping:
          bosh-io-release: bpm-bosh-io-release
          repo: kong-boshrelease-master
        params:
          RELEASE_NAME:  bpm
          MANIFEST_PATH: deploy/gk-kong.yml

      - task: git-commit
        image: gk-ops-image
        file: gk-automation/tasks/git/commit.yml
        input_mapping:
          repo: repo-bumped
        params:
          GIT_COMMIT_NAME:  ((git-commit-name))
          GIT_COMMIT_EMAIL: ((git-commit-email))

      - put: kong-boshrelease-master
        params:
          repository: repo-committed
          rebase:     true

  - name: detect-postgres
    serial: true
    serial_groups: [ detect ]
    plan:
      - in_parallel:
          - get: postgres-bosh-io-release
            trigger: true
            params: { tarball: false }
          - get: kong-boshrelease-master
          - get: gk-automation
          - get: gk-ops-image

      - task: bump-postgres
        image: gk-ops-image
        file: gk-automation/tasks/boshrelease/depl-manifest-release-bump.yml
        input_mapping:
          bosh-io-release: postgres-bosh-io-release
          repo: kong-boshrelease-master
        params:
          RELEASE_NAME:  postgres
          MANIFEST_PATH: deploy/gk-kong.yml

      - task: git-commit
        image: gk-ops-image
        file: gk-automation/tasks/git/commit.yml
        input_mapping:
          repo: repo-bumped
        params:
          GIT_COMMIT_NAME:  ((git-commit-name))
          GIT_COMMIT_EMAIL: ((git-commit-email))

      - put: kong-boshrelease-master
        params:
          repository: repo-committed
          rebase:     true

  - name: detect-os-conf
    serial: true
    serial_groups: [ detect ]
    plan:
      - in_parallel:
          - get: os-conf-bosh-io-release
            trigger: true
            params: { tarball: false }
          - get: kong-boshrelease-master
          - get: gk-automation
          - get: gk-ops-image

      - task: bump-os-conf
        image: gk-ops-image
        file: gk-automation/tasks/boshrelease/depl-manifest-release-bump.yml
        input_mapping:
          bosh-io-release: os-conf-bosh-io-release
          repo: kong-boshrelease-master
        params:
          RELEASE_NAME:  os-conf
          MANIFEST_PATH: deploy/gk-kong.yml

      - task: git-commit
        image: gk-ops-image
        file: gk-automation/tasks/git/commit.yml
        input_mapping:
          repo: repo-bumped
        params:
          GIT_COMMIT_NAME:  ((git-commit-name))
          GIT_COMMIT_EMAIL: ((git-commit-email))

      - put: kong-boshrelease-master
        params:
          repository: repo-committed
          rebase:     true
