---

# Update the BOSH DNS alias used for the admin API, in order to target the
# 'kong-control' instance group
- path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/domain=_.admin-api.service.kong.internal/targets
  type: replace
  value:
    - query: _
      instance_group: kong-control
      network: ((network_name))
      deployment: ((deployment_name))
      domain: bosh
